language: php
php: 7.2
before_install:
  - composer self-update
  - composer config repositories.packagist.com composer https://repo.packagist.com/snowio/
  - if [[ -n $PACKAGIST_TOKEN ]]; then composer config http-basic.repo.packagist.com token $PACKAGIST_TOKEN; fi
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
cache:
  directories: $HOME/.composer/cache
before_script: composer install --no-interaction --dev
script: vendor/bin/phpunit --coverage-clover=coverage.xml
after_success: bash <(curl -s https://codecov.io/bash)